// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $copy_index from "./routes/copy/index.jsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.jsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $check_Check from "./islands/check/Check.jsx";
import * as $check_check_data from "./islands/check/check-data.js";
import * as $check_check_store from "./islands/check/check-store.js";
import * as $check_copy from "./islands/check/copy.jsx";
import * as $check_copyToClipboard from "./islands/check/copyToClipboard.js";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/copy/index.jsx": $copy_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.jsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/check/Check.jsx": $check_Check,
    "./islands/check/check-data.js": $check_check_data,
    "./islands/check/check-store.js": $check_check_store,
    "./islands/check/copy.jsx": $check_copy,
    "./islands/check/copyToClipboard.js": $check_copyToClipboard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
